name: audio_recorder
description: A Flutter plugin to record audio.
version: 1.0.3
homepage: https://github.com/ZaraclaJ/audio_recorder

dependencies:
  path: ^1.5.1
  file: ^5.0.4
  flutter:
    sdk: flutter
  audio_recorder_platform_interface:
    #git:
    #  url: git://github.com/nmfisher/audio_recorder.git
    #  path: audio_recorder_platform_interface
    path: ../audio_recorder_platform_interface
  audio_recorder_web:
    #git:
    #  url: git://github.com/nmfisher/audio_recorder.git
      
    #  path: audio_recorder_web
    path: ../audio_recorder_web

environment:
  sdk: ">=2.0.0-dev.40.0.flutter-f981f09760 <3.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.jordanalcaraz.audiorecorder.audiorecorder
        pluginClass: AudioRecorderPlugin
      ios:
        pluginClass: AudioRecorderPlugin
      web:
        default_package: audio_recorder_web

dev_dependencies:
  plugin_platform_interface: ^1.0.0
  flutter_test:
    sdk: flutter
  test: ^1.3.0
  path_provider: ^1.1.0