name: audio_recorder
description: A Flutter plugin to record audio.
version: 1.0.3
homepage: https://github.com/ZaraclaJ/audio_recorder

dependencies:
  path: ^1.5.1
  file: ^5.0.4
  permission_handler: ^5.0.0+hotfix.3
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.40.0.flutter-f981f09760 <3.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.jordanalcaraz.audiorecorder.audiorecorder
        pluginClass: AudioRecorderPlugin
      ios:
        pluginClass: AudioRecorderPlugin
      web:
        pluginClass: AudioRecorderWebPlugin
        fileName: audio_recorder_web.dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0
  path_provider: ^1.1.0