name: audio_recorder_web
description: A web implementation for the Flutter audio_recorder plugin.
version: 1.0.3
homepage: https://github.com/ZaraclaJ/audio_recorder

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.0
  audio_recorder_platform_interface:
    #git:
    #  url: git://github.com/nmfisher/audio_recorder.git
    #  path: audio_recorder_platform_interface
    path: ../audio_recorder_platform_interface
  meta: ^1.0.5


environment:
  sdk: ">=2.0.0-dev.40.0.flutter-f981f09760 <3.0.0"

flutter:
  plugin:
    platforms:
      web:
        pluginClass: AudioRecorderWebPlugin
        fileName: audio_recorder_web.dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0
  path_provider: ^1.1.0