name: audio_recorder_platform_interface
description: A Flutter plugin to record audio.
version: 1.0.3
homepage: https://github.com/nmfisher/audio_recorder

dependencies:
  path: ^1.5.1
  file: ^5.0.4
  permission_handler: ^5.0.0+hotfix.3
  plugin_platform_interface: ^1.0.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.40.0.flutter-f981f09760 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0
  path_provider: ^1.1.0